### PR TITLE
fix: dataset initialization

### LINKED ISSUE #54: Hashing in light and fast mode give different results
I'm trying to implement a proof of work and its verification. The proving should use the _fast_ mode, while verification - _light_. However, I'm failing to make it work, the light VM returns different hashes for the same input. I expect both to return the same hash. I'm unsure if I'm using RandomX properly - could you help?

Here's a minimal test that fails:
```rust

#[test]
fn randomx_hash_fast_vs_light() {
    let input = b"input";
    let key = b"key";

    let cache = RandomXCache::new(RandomXFlag::FLAG_DEFAULT, key).unwrap();
    let dataset = RandomXDataset::new(RandomXFlag::FLAG_DEFAULT, cache.clone(), 0).unwrap();
    let fast_vm = RandomXVM::new(
        RandomXFlag::FLAG_HARD_AES | RandomXFlag::FLAG_FULL_MEM,
        Some(cache),
        Some(dataset),
    )
    .unwrap();

    let cache = RandomXCache::new(RandomXFlag::FLAG_DEFAULT, key).unwrap();
    let dataset = RandomXDataset::new(RandomXFlag::FLAG_DEFAULT, cache.clone(), 0).unwrap();
    let light_vm = RandomXVM::new(RandomXFlag::FLAG_HARD_AES, Some(cache), Some(dataset)).unwrap();

    let fast = fast_vm.calculate_hash(input).unwrap();
    let light = light_vm.calculate_hash(input).unwrap();
    assert_eq!(fast, light);
}
```
```sh
---- tests::randomx_hash_fast_vs_light stdout ----
thread 'tests::randomx_hash_fast_vs_light' panicked at 'assertion failed: `(left == right)`
  left: `[167, 233, 27, 2, 242, 232, 157, 112, 180, 51, 158, 61, 223, 56, 79, 10, 59, 180, 15, 197, 102, 64, 227, 3, 92, 119, 17, 45, 168, 85, 221, 180]`,
 right: `[46, 44, 66, 118, 196, 74, 91, 214, 215, 78, 199, 115, 206, 141, 89, 33, 28, 12, 213, 87, 88, 170, 103, 218, 161, 162, 49, 100, 85, 218, 102, 211]`', src/lib.rs:684:9
```

I pushed the test to https://github.com/poszu/randomx-rs/blob/7bd6939ef204ea56bc2764f0a5314aaa896676c6/src/lib.rs#L664-L685

### PR DESCRIPTION
**Pull request by poszu**
Closes #54 

### Motivation
I looked over the tests in the RandomX C library and I found discrepancies in dataset initialization. [The docs say](https://github.com/tevador/RandomX/blob/040f4500a6e79d54d84a668013a94507045e786f/src/randomx.h#L150-L151):
> In order to use the Dataset, all items from 0 to (randomx_dataset_item_count() - 1) must be initialized.

In effect, all hashes calculated in _fast_ mode (`FLAG_FULL_MEM`) are invalid.
 
### Changes:
- added a few tests for hashing in both _light_ and _fast_ modes using the vectors borrowed from https://github.com/tevador/RandomX/blob/040f4500a6e79d54d84a668013a94507045e786f/src/tests/tests.cpp#L963-L985;
- fixed `RandomXDataset` initialization so that all `randomx_dataset_item_count()` items are initialized;
- changed `RandomXDataset::count()` into an associated function as it is only a wrapper over `randomx_dataset_item_count()` and it doesn't require an instance in order to be called.

### CODE REVIEW

File: src/bindings.rs [hunk 1]
```diff
@@ -22,6 +22,7 @@
 
 use libc::{c_uint, c_ulong, c_void};
 pub const RANDOMX_HASH_SIZE: u32 = 32;
+#[allow(dead_code)]
 pub const RANDOMX_DATASET_ITEM_SIZE: u32 = 64;
```
Comment (hansieodendaal) [inline src/bindings.rs]:
```suggestion
```

**Review by hansieodendaal — COMMENTED** [review]
utACK

File: src/bindings.rs (hunk 1 above)
Comment (poszu) [reply src/bindings.rs]: :+1: I was also thinking to remove it entirely.

**Review by SWvheerden — COMMENTED** [review]
Looks goodf, just remove that dead code

**Comment by poszu** [comment]
@SWvheerden is there anything else I need to do?

**Review by SWvheerden — APPROVED** [review]

**Comment by SWvheerden** [comment]
Thanks for the ping, this slipped under the radar.

**Comment by SWvheerden** [comment]
Is it possible to rebase the commits and sign them with gpg?
I see you singed commit [d98bd3a](https://github.com/tari-project/randomx-rs/pull/55/commits/d98bd3a84e591caee84112146cc499dfb5be3763), but not the rest?

The project is blocking me from merging unless all commits are singed.

**Comment by poszu** [comment]
@SWvheerden 
> Is it possible to rebase the commits and sign them with gpg? I see you singed commit [d98bd3a](https://github.com/tari-project/randomx-rs/pull/55/commits/d98bd3a84e591caee84112146cc499dfb5be3763), but not the rest?
> 
> The project is blocking me from merging unless all commits are singed.

Done

**Comment by poszu** [comment]
@SWvheerden ping
